apiVersion: v1
data:
  version-manifest.yml: |
    applications:
{{- range $key, $value := .Values.versions}}
    - application: {{ $key }}
      version: {{ $value }}
      linkAddress: https://github.com/rht-labs
{{- end }}
kind: ConfigMap
metadata:
  name: version-cm
