apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lodestar-status-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: lodestar-status